FROM ubuntu:lasted AS build

RUN apt_get update
RUN apt_get install openjdk-17-jdk -y

COPY . .

RUN apt_get install maven -y
RUN mvn clean install

EXPOSE 8080

COPY --from=build /target/todolist-1.0.0.jar app.jar

ENTRYPOINT [ "java", "-jar", "app.jar" ]

